version: '3'

services:
    ubuntu:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./server:/etc/nginx
            - ./www:/var/www/mysite
        container_name: ngubuntu
        networks:
            - ng-app-network

networks:
    ng-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"